name: Laravel DEV
on:
  push:
    branches:
      - develop
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:14-3.3
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pap_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
      - name: Copy .env
        run: cp .env.example .env
      - name: Configure test DB in .env
        run: |
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_DATABASE=pap/DB_DATABASE=pap_test/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=password/' .env
          sed -i 's/CACHE_DRIVER=file/CACHE_DRIVER=array/' .env
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress -o
      - name: Generate key
        run: php artisan key:generate
      - name: Enable PostGIS extension
        run: PGPASSWORD=password psql -h 127.0.0.1 -U root -d pap_test -c "CREATE EXTENSION IF NOT EXISTS postgis;"
      - name: Migrate test DB
        run: php artisan migrate --force
      - name: Laravel Tests
        run: php artisan test
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /var/www/html/dev.portapporta && ./scripts/deploy_dev.sh"
  launch-horizon:
    name: Launch Horizon
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: SSH connection and run scripts/launch_horizon.sh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /var/www/html/dev.portapporta && bash scripts/launch_horizon.sh DEV"
